apt_packages:
  - kali-linux-headless
  - kali-linux-firmware
  - kali-linux-core
  - spice-webdavd
  - spice-vdagent
  - qemu-guest-agent
  - open-vm-tools
  - libnss3-tools
  - curl
  - openssl
  - jq
  - xq
  - libreoffice
  - seclists
  - htop
  - brasero
  - gron
  - keepassxc
  - gimp
  - krita
  - strace
  - ltrace
  - gdb
  - qemu-kvm
  - libvirt-daemon-system
  - libvirt-clients
  - libvirt-dev
  - virt-manager
  - bridge-utils
  - virt-install
  - libosinfo-bin
  - spice-vdagent
  - dnsmasq-base
  - ovmf
  - handbrake
  - ffmpeg
  - lame
  - vorbis-tools
  - audacity
  - krb5-user
  - krb5-config
  - krb5-locales
  - ldap-utils
  - dnsutils
  - python3-impacket
  - bloodhound
  - neo4j
  - python3-ldap3
  - python3-dnspython
  - golang
  - xplico
