# Playbook with everything in it
# To get everything:
# ansible-playbook everything.yml -i "10.20.30.40," -K -k --ask-vault-pass
#
# If you will have internet you can skip offline and extra download tasks:
# ansible-playbook everything.yml -i "10.20.30.40," -K -k --skip-tags=offline,downloads --ask-vault-pass
#
- name: Configure Kali host
  hosts: all
  become: true
  vars_files:
    - vars/licenses.yml
    - vars/vars.yml

  roles:
    - role: system_update
      tags: system_update
    - role: locale
      tags: locale
    - role: sublime
      tags: sublime
    - role: packages
      tags: packages
    - role: firefox
      tags: firefox
    - role: burpsuite
      tags: burpsuite
    - role: helper_scripts
      tags: helper_scripts
    - role: nessus_pro
      tags: nessus_pro
    - role: panel
      tags: panel
    - role: github_repos
      tags: repos
    - role: downloads
      tags: downloads
    - role: screensaver_disable
      tags: screensaver_disable
    - role: shared_folders
      tags: shared_folders
    - role: smartcard
      tags: smartcard
    - role: reference
      tags: reference
    - role: offline
      tags: offline
    - role: kubernetes
      tags: kubernetes

  post_tasks:
    - name: Warn if reboot is required
      debug:
        msg: "REBOOT REQUIRED — please reboot this host manually when ready"
      when: reboot_required.stat.exists

